// Generated by CIRCT firtool-1.62.1
module Core(
  input         clock,
                reset,
  input  [31:0] io_instr,
  output [31:0] io_pc,
                io_result
);

  wire [31:0] _regfile_io_rdata1;
  wire [31:0] _exu_io_result;
  wire [4:0]  _idu_io_rs1;
  wire [4:0]  _idu_io_rd;
  wire [31:0] _idu_io_imm;
  wire        _idu_io_rf_wen;
  IFU ifu (
    .clock (clock),
    .reset (reset),
    .io_pc (io_pc)
  );
  IDU idu (
    .io_instr  (io_instr),
    .io_rs1    (_idu_io_rs1),
    .io_rd     (_idu_io_rd),
    .io_imm    (_idu_io_imm),
    .io_rf_wen (_idu_io_rf_wen)
  );
  EXU exu (
    .io_val1   (_regfile_io_rdata1),
    .io_val2   (_idu_io_imm),
    .io_result (_exu_io_result)
  );
  RegFile regfile (
    .clock     (clock),
    .io_wdata  (_exu_io_result),
    .io_waddr  (_idu_io_rd[3:0]),
    .io_wen    (_idu_io_rf_wen),
    .io_raddr1 (_idu_io_rs1[3:0]),
    .io_rdata1 (_regfile_io_rdata1)
  );
  ebreak ebreak (
    .instr (io_instr)
  );
  assign io_result = _exu_io_result;
endmodule

