// Generated by CIRCT firtool-1.62.1
module EXU(
  input  [4:0]  io_alu_op,
  input  [31:0] io_val1,
                io_val2,
  output [31:0] io_result,
  input  [2:0]  io_csr_alu_op,
  output [31:0] io_csr_result
);

  wire [32:0] _diff_T_2 = {1'h0, io_val1} - {1'h0, io_val2};
  wire [31:0] _sum_T = io_val1 + io_val2;
  wire [31:0] _diff_s_T_2 = io_val1 - io_val2;
  wire        le =
    io_val1[31] != io_val2[31] & io_val2[31] == _diff_s_T_2[31] ^ _diff_s_T_2[31];
  wire        less = le & (|(_diff_T_2[31:0]));
  wire [31:0] _GEN = {27'h0, io_val2[4:0]};
  wire [62:0] sllvalue = {31'h0, io_val1} << io_val2[4:0];
  wire [31:0] or_0 = io_val1 | io_val2;
  assign io_result =
    io_alu_op == 5'h1
      ? _sum_T
      : io_alu_op == 5'h2
          ? _sum_T & 32'hFFFFFFFE
          : io_alu_op == 5'h3
              ? {31'h0, _diff_T_2[32]}
              : io_alu_op == 5'h4
                  ? {31'h0, ~(|(_diff_T_2[31:0]))}
                  : io_alu_op == 5'h5
                      ? _diff_T_2[31:0]
                      : io_alu_op == 5'h6
                          ? io_val1 ^ io_val2
                          : io_alu_op == 5'h7
                              ? $signed($signed(io_val1) >>> _GEN)
                              : io_alu_op == 5'h8
                                  ? sllvalue[31:0]
                                  : io_alu_op == 5'h9
                                      ? io_val1 & io_val2
                                      : io_alu_op == 5'hA
                                          ? or_0
                                          : io_alu_op == 5'hB
                                              ? {31'h0, le}
                                              : io_alu_op == 5'hC
                                                  ? {31'h0, |(_diff_T_2[31:0])}
                                                  : io_alu_op == 5'hD
                                                      ? io_val1 >> _GEN
                                                      : io_alu_op == 5'hE
                                                          ? {31'h0, _diff_T_2[32]}
                                                          : io_alu_op == 5'hF
                                                              ? {31'h0, ~(_diff_T_2[32])}
                                                              : io_alu_op == 5'h10
                                                                  ? {31'h0, less}
                                                                  : io_alu_op == 5'h11
                                                                      ? {31'h0, ~less}
                                                                      : io_alu_op == 5'h12
                                                                          ? io_val2
                                                                          : 32'h0;
  assign io_csr_result =
    io_csr_alu_op == 3'h1 ? io_val1 : io_csr_alu_op == 3'h2 ? or_0 : 32'h0;
endmodule

