// Generated by CIRCT firtool-1.62.1
module IDU(
  input         clock,
                reset,
                io_in_from_ifu_valid,
  input  [31:0] io_in_from_ifu_bits_instr,
                io_in_from_ifu_bits_pc,
                io_in_from_ifu_bits_snpc,
  output [11:0] io_out_to_csr_csr_r_addr,
  output [4:0]  io_out_to_regfile_rs1_addr,
                io_out_to_regfile_rs2_addr,
  output        io_out_to_exu_valid,
  output [4:0]  io_out_to_exu_bits_alu_op,
  output [2:0]  io_out_to_exu_bits_alu_op1_sel,
                io_out_to_exu_bits_alu_op2_sel,
                io_out_to_exu_bits_rf_wdata_sel,
  output        io_out_to_exu_bits_rf_wen,
  output [31:0] io_out_to_exu_bits_imm,
  output [4:0]  io_out_to_exu_bits_rd_addr,
  output        io_out_to_exu_bits_mem_wen,
                io_out_to_exu_bits_mem_ren,
  output [11:0] io_out_to_exu_bits_csr_r_w_addr,
  output [1:0]  io_out_to_exu_bits_csr_r_w_ctrl,
  output [31:0] io_out_to_exu_bits_pc,
                io_out_to_exu_bits_snpc,
  output [1:0]  io_out_to_exu_bits_jump_op,
  output [2:0]  io_out_to_exu_bits_load_store_range,
                io_out_to_exu_bits_csr_alu_op
);

  reg         valid_to_exu;
  reg         state;
  reg  [31:0] instr;
  reg  [31:0] pc;
  reg  [31:0] snpc;
  wire [9:0]  _GEN = {instr[14:12], instr[6:0]};
  wire        _csignals_T_1 = _GEN == 10'h13;
  wire        _csignals_T_3 = instr[6:0] == 7'h17;
  wire        _csignals_T_5 = instr[6:0] == 7'h37;
  wire        _csignals_T_7 = instr[6:0] == 7'h6F;
  wire        _csignals_T_9 = _GEN == 10'h67;
  wire        _csignals_T_11 = _GEN == 10'h103;
  wire        _csignals_T_13 = _GEN == 10'h123;
  wire        _csignals_T_15 = _GEN == 10'h193;
  wire        _csignals_T_17 = _GEN == 10'hE3;
  wire [16:0] _GEN_0 = {instr[31:25], instr[14:12], instr[6:0]};
  wire        _csignals_T_19 = _GEN_0 == 17'h8033;
  wire        _csignals_T_21 = _GEN_0 == 17'h33;
  wire        _csignals_T_23 = _GEN_0 == 17'h233;
  wire        _csignals_T_25 = _GEN_0 == 17'h1B3;
  wire        _csignals_T_27 = _GEN_0 == 17'h8293;
  wire        _csignals_T_29 = _GEN == 10'h203;
  wire        _csignals_T_31 = _GEN == 10'hA3;
  wire        _csignals_T_33 = _GEN_0 == 17'hB3;
  wire        _csignals_T_35 = _GEN_0 == 17'h3B3;
  wire        _csignals_T_37 = _GEN == 10'h393;
  wire        _csignals_T_39 = _GEN == 10'h213;
  wire        _csignals_T_41 = _GEN_0 == 17'h333;
  wire        _csignals_T_43 = _GEN == 10'h23;
  wire        _csignals_T_45 = _GEN == 10'h2E3;
  wire        _csignals_T_47 = _GEN == 10'h63;
  wire        _csignals_T_49 = _GEN_0 == 17'h293;
  wire        _csignals_T_51 = _GEN_0 == 17'h93;
  wire        _csignals_T_53 = _GEN == 10'h3E3;
  wire        _csignals_T_55 = _GEN == 10'h363;
  wire        _csignals_T_57 = _GEN_0 == 17'h133;
  wire        _csignals_T_59 = _GEN == 10'h263;
  wire        _csignals_T_61 = _GEN == 10'h83;
  wire        _csignals_T_63 = _GEN == 10'h283;
  wire        _csignals_T_65 = _GEN_0 == 17'h82B3;
  wire        _csignals_T_67 = _GEN_0 == 17'h2B3;
  wire        _csignals_T_69 = _GEN == 10'h3;
  wire        _csignals_T_71 = _GEN == 10'h313;
  wire        _csignals_T_73 = _GEN == 10'h113;
  wire        _csignals_T_75 = _GEN == 10'hF3;
  wire        _csignals_T_84 = _GEN == 10'h173;
  wire        _csignals_T_79 = instr == 32'h73;
  wire        _csignals_T_81 = instr == 32'h30200073;
  wire        _GEN_1 = _csignals_T_53 | _csignals_T_55;
  wire        _GEN_2 = _csignals_T_49 | _csignals_T_51;
  wire        _GEN_3 = _csignals_T_45 | _csignals_T_47;
  wire        _GEN_4 = _csignals_T_43 | _GEN_3;
  wire        _GEN_5 =
    _csignals_T_33 | _csignals_T_35 | _csignals_T_37 | _csignals_T_39 | _csignals_T_41;
  wire        _GEN_6 = _csignals_T_27 | _csignals_T_29;
  wire        _GEN_7 = _csignals_T_9 | _csignals_T_11;
  wire        csignals_0 =
    _csignals_T_1 | _csignals_T_3 | _csignals_T_5 | _csignals_T_7 | _GEN_7
    | ~_csignals_T_13
    & (_csignals_T_15 | ~_csignals_T_17
       & (_csignals_T_19 | _csignals_T_21 | _csignals_T_23 | _csignals_T_25 | _GEN_6
          | ~_csignals_T_31
          & (_GEN_5 | ~_GEN_4
             & (_GEN_2 | ~_GEN_1
                & (_csignals_T_57 | ~_csignals_T_59
                   & (_csignals_T_61 | _csignals_T_63 | _csignals_T_65 | _csignals_T_67
                      | _csignals_T_69 | _csignals_T_71 | _csignals_T_73 | _csignals_T_75
                      | _csignals_T_84))))));
  wire        _GEN_8 = _csignals_T_75 | _csignals_T_84;
  wire        _GEN_9 = _csignals_T_71 | _csignals_T_73 | _GEN_8;
  wire        _GEN_10 =
    _csignals_T_61 | _csignals_T_63 | _csignals_T_65 | _csignals_T_67 | _csignals_T_69
    | _GEN_9;
  wire        _GEN_11 = _csignals_T_69 | _csignals_T_71 | _csignals_T_73;
  wire        _GEN_12 = _csignals_T_65 | _csignals_T_67;
  wire        _GEN_13 = _csignals_T_61 | _csignals_T_63;
  wire        _GEN_14 = _csignals_T_3 | _csignals_T_5;
  wire [2:0]  csignals_2 =
    _csignals_T_1
      ? 3'h1
      : _GEN_14
          ? 3'h2
          : _csignals_T_7
              ? 3'h3
              : _GEN_7
                  ? 3'h1
                  : _csignals_T_13
                      ? 3'h4
                      : _csignals_T_15
                          ? 3'h1
                          : _csignals_T_17
                              ? 3'h5
                              : _csignals_T_19 | _csignals_T_21 | _csignals_T_23
                                | _csignals_T_25
                                  ? 3'h0
                                  : _GEN_6
                                      ? 3'h1
                                      : _csignals_T_31
                                          ? 3'h4
                                          : _csignals_T_33 | _csignals_T_35
                                              ? 3'h0
                                              : _csignals_T_37 | _csignals_T_39
                                                  ? 3'h1
                                                  : _csignals_T_41
                                                      ? 3'h0
                                                      : _csignals_T_43
                                                          ? 3'h4
                                                          : _GEN_3
                                                              ? 3'h5
                                                              : _GEN_2
                                                                  ? 3'h1
                                                                  : _GEN_1
                                                                      ? 3'h5
                                                                      : _csignals_T_57
                                                                          ? 3'h0
                                                                          : _csignals_T_59
                                                                              ? 3'h5
                                                                              : _GEN_13
                                                                                  ? 3'h1
                                                                                  : _GEN_12
                                                                                      ? 3'h0
                                                                                      : _GEN_11
                                                                                          ? 3'h1
                                                                                          : _GEN_8
                                                                                              ? 3'h6
                                                                                              : 3'h0;
  wire        _GEN_15 =
    _csignals_T_19 | _csignals_T_21 | _csignals_T_23 | _csignals_T_25 | _csignals_T_27;
  wire        _GEN_16 = _csignals_T_7 | _csignals_T_9;
  wire        _GEN_17 = _csignals_T_1 | _GEN_14;
  wire        _GEN_18 = _csignals_T_11 | _csignals_T_13;
  wire        _GEN_19 =
    _csignals_T_45 | _csignals_T_47 | _csignals_T_49 | _csignals_T_51 | _csignals_T_53
    | _csignals_T_55 | _csignals_T_57 | _csignals_T_59;
  wire        _GEN_20 = _csignals_T_15 | _csignals_T_17 | _GEN_15;
  wire        _GEN_21 = _csignals_T_1 | _csignals_T_3 | _csignals_T_5 | _GEN_16;
  wire [1:0]  csignals_6 =
    _GEN_21
      ? 2'h0
      : _csignals_T_11
          ? 2'h2
          : _csignals_T_13
              ? 2'h1
              : _GEN_20
                  ? 2'h0
                  : _csignals_T_29
                      ? 2'h2
                      : _csignals_T_31
                          ? 2'h1
                          : _GEN_5
                              ? 2'h0
                              : _csignals_T_43
                                  ? 2'h1
                                  : _GEN_19
                                      ? 2'h0
                                      : _GEN_13
                                          ? 2'h2
                                          : _GEN_12 ? 2'h0 : {_csignals_T_69, 1'h0};
  wire        _GEN_22 =
    _csignals_T_1 | _csignals_T_3 | _csignals_T_5 | _csignals_T_7 | _csignals_T_9
    | _csignals_T_11 | _csignals_T_13 | _csignals_T_15 | _csignals_T_17 | _csignals_T_19
    | _csignals_T_21 | _csignals_T_23 | _csignals_T_25 | _csignals_T_27 | _csignals_T_29
    | _csignals_T_31 | _csignals_T_33 | _csignals_T_35 | _csignals_T_37 | _csignals_T_39
    | _csignals_T_41 | _csignals_T_43 | _csignals_T_45 | _csignals_T_47 | _csignals_T_49
    | _csignals_T_51 | _csignals_T_53 | _csignals_T_55 | _csignals_T_57 | _csignals_T_59
    | _csignals_T_61 | _csignals_T_63 | _csignals_T_65 | _csignals_T_67 | _GEN_11;
  wire [1:0]  csignals_8 =
    _GEN_22 ? 2'h0 : _GEN_8 ? 2'h1 : _csignals_T_79 ? 2'h2 : {2{_csignals_T_81}};
  reg  [31:0] casez_tmp;
  always_comb begin
    casez (csignals_2)
      3'b000:
        casez_tmp = 32'h0;
      3'b001:
        casez_tmp = {{20{instr[31]}}, instr[31:20]};
      3'b010:
        casez_tmp = {instr[31:12], 12'h0};
      3'b011:
        casez_tmp = {{12{instr[31]}}, instr[19:12], instr[20], instr[30:21], 1'h0};
      3'b100:
        casez_tmp = {{20{instr[31]}}, instr[31:25], instr[11:7]};
      3'b101:
        casez_tmp = {{20{instr[31]}}, instr[7], instr[30:25], instr[11:8], 1'h0};
      3'b110:
        casez_tmp = 32'h0;
      default:
        casez_tmp = 32'h0;
    endcase
  end // always_comb
  wire        _io_out_to_exu_bits_csr_r_w_addr_T = csignals_8 == 2'h1;
  always @(posedge clock) begin
    if (reset) begin
      valid_to_exu <= 1'h0;
      state <= 1'h0;
      instr <= 32'h0;
      pc <= 32'h0;
      snpc <= 32'h0;
    end
    else begin
      valid_to_exu <= ~state & (io_in_from_ifu_valid | valid_to_exu);
      state <= ~state & valid_to_exu;
      if (io_in_from_ifu_valid) begin
        instr <= io_in_from_ifu_bits_instr;
        pc <= io_in_from_ifu_bits_pc;
        snpc <= io_in_from_ifu_bits_snpc;
      end
    end
  end // always @(posedge)
  assign io_out_to_csr_csr_r_addr =
    _io_out_to_exu_bits_csr_r_w_addr_T ? instr[31:20] : 12'h0;
  assign io_out_to_regfile_rs1_addr = instr[19:15];
  assign io_out_to_regfile_rs2_addr = instr[24:20];
  assign io_out_to_exu_valid = valid_to_exu;
  assign io_out_to_exu_bits_alu_op =
    _csignals_T_1 | _csignals_T_3 | _csignals_T_5 | _csignals_T_7
      ? 5'h1
      : _csignals_T_9
          ? 5'h2
          : _GEN_18
              ? 5'h1
              : _csignals_T_15
                  ? 5'h3
                  : _csignals_T_17
                      ? 5'h4
                      : _csignals_T_19
                          ? 5'h5
                          : _csignals_T_21
                              ? 5'h1
                              : _csignals_T_23
                                  ? 5'h6
                                  : _csignals_T_25
                                      ? 5'h3
                                      : _csignals_T_27
                                          ? 5'h7
                                          : _csignals_T_29 | _csignals_T_31
                                              ? 5'h1
                                              : _csignals_T_33
                                                  ? 5'h8
                                                  : _csignals_T_35 | _csignals_T_37
                                                      ? 5'h9
                                                      : _csignals_T_39
                                                          ? 5'h6
                                                          : _csignals_T_41
                                                              ? 5'hA
                                                              : _csignals_T_43
                                                                  ? 5'h1
                                                                  : _csignals_T_45
                                                                      ? 5'hB
                                                                      : _csignals_T_47
                                                                          ? 5'hC
                                                                          : _csignals_T_49
                                                                              ? 5'hD
                                                                              : _csignals_T_51
                                                                                  ? 5'h8
                                                                                  : _csignals_T_53
                                                                                      ? 5'hE
                                                                                      : _csignals_T_55
                                                                                          ? 5'hF
                                                                                          : _csignals_T_57
                                                                                              ? 5'h10
                                                                                              : _csignals_T_59
                                                                                                  ? 5'h11
                                                                                                  : _GEN_13
                                                                                                      ? 5'h1
                                                                                                      : _csignals_T_65
                                                                                                          ? 5'h7
                                                                                                          : _csignals_T_67
                                                                                                              ? 5'hD
                                                                                                              : _csignals_T_69
                                                                                                                  ? 5'h1
                                                                                                                  : _csignals_T_71
                                                                                                                      ? 5'hA
                                                                                                                      : _csignals_T_73
                                                                                                                          ? 5'h10
                                                                                                                          : _GEN_8
                                                                                                                              ? 5'h12
                                                                                                                              : 5'h0;
  assign io_out_to_exu_bits_alu_op1_sel =
    _csignals_T_1
      ? 3'h1
      : _csignals_T_3
          ? 3'h2
          : _csignals_T_5
              ? 3'h0
              : _csignals_T_7
                  ? 3'h2
                  : {2'h0,
                     _csignals_T_9 | _csignals_T_11 | _csignals_T_13 | _csignals_T_15
                       | _csignals_T_17 | _csignals_T_19 | _csignals_T_21 | _csignals_T_23
                       | _csignals_T_25 | _csignals_T_27 | _csignals_T_29 | _csignals_T_31
                       | _csignals_T_33 | _csignals_T_35 | _csignals_T_37 | _csignals_T_39
                       | _csignals_T_41 | _csignals_T_43 | _csignals_T_45 | _csignals_T_47
                       | _csignals_T_49 | _csignals_T_51 | _csignals_T_53 | _csignals_T_55
                       | _csignals_T_57 | _csignals_T_59 | _GEN_10};
  assign io_out_to_exu_bits_alu_op2_sel = csignals_2;
  assign io_out_to_exu_bits_rf_wdata_sel =
    _GEN_17
      ? 3'h1
      : _GEN_16
          ? 3'h2
          : _csignals_T_11
              ? 3'h3
              : _csignals_T_13
                  ? 3'h0
                  : _csignals_T_15
                      ? 3'h1
                      : _csignals_T_17
                          ? 3'h0
                          : _GEN_15
                              ? 3'h1
                              : _csignals_T_29
                                  ? 3'h3
                                  : _csignals_T_31
                                      ? 3'h0
                                      : _GEN_5
                                          ? 3'h1
                                          : _GEN_4
                                              ? 3'h0
                                              : _GEN_2
                                                  ? 3'h1
                                                  : _GEN_1
                                                      ? 3'h0
                                                      : _csignals_T_57
                                                          ? 3'h1
                                                          : _csignals_T_59
                                                              ? 3'h0
                                                              : _GEN_13
                                                                  ? 3'h3
                                                                  : _GEN_12
                                                                      ? 3'h1
                                                                      : _csignals_T_69
                                                                          ? 3'h3
                                                                          : {2'h0,
                                                                             _GEN_9};
  assign io_out_to_exu_bits_rf_wen = csignals_0;
  assign io_out_to_exu_bits_imm = casez_tmp;
  assign io_out_to_exu_bits_rd_addr = csignals_0 ? instr[11:7] : 5'h0;
  assign io_out_to_exu_bits_mem_wen = csignals_6 == 2'h1;
  assign io_out_to_exu_bits_mem_ren = csignals_6 == 2'h2;
  assign io_out_to_exu_bits_csr_r_w_addr =
    _io_out_to_exu_bits_csr_r_w_addr_T ? instr[31:20] : 12'h0;
  assign io_out_to_exu_bits_csr_r_w_ctrl = csignals_8;
  assign io_out_to_exu_bits_pc = pc;
  assign io_out_to_exu_bits_snpc = snpc;
  assign io_out_to_exu_bits_jump_op =
    _GEN_17
      ? 2'h0
      : _GEN_16
          ? 2'h1
          : _csignals_T_11 | _csignals_T_13 | _csignals_T_15
              ? 2'h0
              : _csignals_T_17
                  ? 2'h2
                  : _csignals_T_19 | _csignals_T_21 | _csignals_T_23 | _csignals_T_25
                    | _csignals_T_27 | _csignals_T_29 | _csignals_T_31 | _csignals_T_33
                    | _csignals_T_35 | _csignals_T_37 | _csignals_T_39 | _csignals_T_41
                    | _csignals_T_43
                      ? 2'h0
                      : _GEN_3
                          ? 2'h2
                          : _GEN_2
                              ? 2'h0
                              : _GEN_1
                                  ? 2'h2
                                  : _csignals_T_57
                                      ? 2'h0
                                      : _csignals_T_59
                                          ? 2'h2
                                          : _GEN_10
                                              ? 2'h0
                                              : {2{_csignals_T_79 | _csignals_T_81}};
  assign io_out_to_exu_bits_load_store_range =
    _GEN_21
      ? 3'h0
      : _GEN_18
          ? 3'h1
          : _GEN_20
              ? 3'h0
              : _csignals_T_29
                  ? 3'h2
                  : _csignals_T_31
                      ? 3'h3
                      : _GEN_5
                          ? 3'h0
                          : _csignals_T_43
                              ? 3'h2
                              : _GEN_19
                                  ? 3'h0
                                  : _csignals_T_61
                                      ? 3'h4
                                      : _csignals_T_63
                                          ? 3'h3
                                          : _GEN_12 | ~_csignals_T_69 ? 3'h0 : 3'h5;
  assign io_out_to_exu_bits_csr_alu_op =
    _GEN_22 ? 3'h0 : _csignals_T_75 ? 3'h1 : {1'h0, _csignals_T_84, 1'h0};
endmodule

