// Generated by CIRCT firtool-1.62.1
module IDU(
  input  [31:0] io_instr,
  output [4:0]  io_rs1,
                io_rd,
  output [31:0] io_imm,
  output        io_rf_wen
);

  assign io_rs1 = io_instr[19:15];
  assign io_rd = io_instr[11:7];
  assign io_imm = {{20{io_instr[31]}}, io_instr[31:20]};
  assign io_rf_wen = {io_instr[14:12], io_instr[6:0]} == 10'h13;
endmodule

