// Generated by CIRCT firtool-1.62.1
module IFU(
  input         clock,
                reset,
  input  [31:0] io_alu_pc,
  input         io_jump_en,
  output [31:0] io_pc,
                io_snpc
);

  reg  [31:0] pc;
  wire [31:0] _snpc_T = pc + 32'h4;
  always @(posedge clock) begin
    if (reset)
      pc <= 32'h80000000;
    else if (io_jump_en)
      pc <= io_alu_pc;
    else
      pc <= _snpc_T;
  end // always @(posedge)
  assign io_pc = pc;
  assign io_snpc = _snpc_T;
endmodule

